export interface GlossaryTerm {
  term: string;
  definition: string;
  category: "finance" | "crypto" | "policy" | "technology";
}

export const glossaryTerms: GlossaryTerm[] = [
  {
    term: "Agentic USD",
    definition: "US dollar stablecoins (such as USDT, USDC) that are fully backed 1:1 by US Treasuries and designed to be used by autonomous AI agents for programmable transactions.",
    category: "crypto",
  },
  {
    term: "Dollarization",
    definition: "The process by which a non-US economy increasingly adopts the US dollar or dollar-denominated assets as a primary medium of exchange and store of value, often at the expense of the domestic currency.",
    category: "finance",
  },
  {
    term: "GENIUS Act",
    definition: "Proposed US legislation that would establish regulatory standards for stablecoins backed by US Treasuries, ensuring compliance and legitimacy for Agentic USD instruments.",
    category: "policy",
  },
  {
    term: "Seigniorage",
    definition: "The profit gained by a government or central bank from issuing currency, particularly the difference between the face value of money and its production cost. Dollarization transfers this profit to the US.",
    category: "finance",
  },
  {
    term: "Legal Tender",
    definition: "Money that is officially recognized by a government as a valid medium for settling debts and making payments. Legal tender status for Agentic USD would give it official legitimacy and widespread acceptance.",
    category: "policy",
  },
  {
    term: "Stablecoin",
    definition: "A cryptocurrency designed to maintain a stable value, typically by being backed by reserves of fiat currency (like US dollars) or other assets.",
    category: "crypto",
  },
  {
    term: "Tokenization",
    definition: "The process of converting real-world assets (such as property, commodities, or financial instruments) into digital tokens that can be traded on blockchain networks.",
    category: "technology",
  },
  {
    term: "Blockchain",
    definition: "A distributed ledger technology that records transactions across multiple computers in a secure, transparent, and immutable manner.",
    category: "technology",
  },
  {
    term: "Smart Contract",
    definition: "Self-executing digital agreements on blockchain networks that automatically enforce and execute terms when predetermined conditions are met.",
    category: "technology",
  },
  {
    term: "Monetary Sovereignty",
    definition: "A nation's ability to independently control its monetary policy, currency supply, and financial system without external interference or dependence.",
    category: "policy",
  },
  {
    term: "Central Bank Digital Currency (CBDC)",
    definition: "A digital form of fiat currency issued and controlled by a central bank, designed to provide the benefits of digital money while maintaining regulatory oversight.",
    category: "finance",
  },
  {
    term: "Hyper-Velocity Capital Flows",
    definition: "The rapid, machine-speed movement of capital across borders and markets, enabled by digital and decentralized financial systems, making traditional monitoring difficult.",
    category: "finance",
  },
  {
    term: "Fiscal Autonomy",
    definition: "A government's ability to independently manage its tax revenue, spending, and debt without external constraints or dependence on foreign financial systems.",
    category: "policy",
  },
  {
    term: "Economic Vassalage",
    definition: "A state of economic dependence where a nation becomes subordinate to another economically dominant power, losing control over key economic levers.",
    category: "policy",
  },
  {
    term: "Programmable Money",
    definition: "Digital currency designed to execute automatically based on coded instructions, enabling conditional payments, automated compliance, and machine-to-machine transactions.",
    category: "technology",
  },
  {
    term: "Double-Backed Stablecoin",
    definition: "A stablecoin collateralized by two distinct asset classes: US Treasuries (for stability) and tokenized real-world assets like property (for yield generation).",
    category: "crypto",
  },
  {
    term: "Yield Pass-Through",
    definition: "A mechanism where returns generated by underlying assets (such as US Treasury interest) are directly passed to holders of a stablecoin or financial instrument.",
    category: "finance",
  },
  {
    term: "Autonomous AI Agent",
    definition: "A software program powered by artificial intelligence that can make independent decisions and execute transactions without human intervention, often optimizing for specific objectives.",
    category: "technology",
  },
];

export function getGlossaryTerm(term: string): GlossaryTerm | undefined {
  return glossaryTerms.find((t) => t.term.toLowerCase() === term.toLowerCase());
}

export function getAllTerms(): string[] {
  return glossaryTerms.map((t) => t.term);
}
